- src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> fix find transformer task for Proguard when using AGP 3.6.x

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> fix when minify is disabled (eg debug), mapping files don't exist

- src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
> improve logs for mapping file provider

- build.gradle
> Let's update the maven package info

- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/pre-merge.yaml
I'm replicating the GH Actions workflow on the `master` branch as apparently Github Actions is not picking up the workflows if they live only in a branch.
> Replicate .github/workflow on master branch

- .editorconfig
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- plugin-build/build.gradle
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
Following up from #53, I'm setting up KtLint and an `.editorconfig` file for Kotlin file.
> Setup KtLint and .editorconfig

- examples/android-gradle-kts/src/main/java/com/example/sampleapp/MainActivity.java
- examples/android-gradle/src/main/java/com/example/sampleapp/MainActivity.java
Just adding a couple of methods to make sure the mapping file has some content.
Fixes #90
Verified that the mapping file contains:
```
com.example.sampleapp.MainActivity -> com.example.sampleapp.MainActivity:
1:1:void helloWorld():0:0 -> onCreate
1:1:void onCreate(android.os.Bundle):0 -> onCreate
```
> Add a dummy method to populate the mapping file

- .github/workflows/pre-merge.yaml
Adding a step in the pre-merge workflow to also assemble the Debug variant
Fixes #88
> Run assembleDebug on pre-merge

- CHANGELOG.md
- plugin-build/download-sentry-cli.sh
Bump: sentry-cli to 1.64.1
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/97
> Bump: sentry-cli to 1.64.1

- .github/workflows/test-maven-publish-maven-local.yaml
- .github/workflows/test-publish-dry-run.yaml
- buildSrc/src/main/java/Dependencies.kt
- plugin-build/build.gradle.kts
Bump vanniktech maven publish and create CI to test publishing to maven local
be sure that publishing still works on CI too when bumping Gradle/maven publish
> Bump vanniktech maven publish and create CI to test publishing to maven local

- .github/workflows/danger.yml
- dangerfile.js
Add Danger changelog checker
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/67
> Add Danger changelog checker

- README.md
Badges for some GHA workflow and callout for the career page
> update readme incl career and badges

- build.gradle.kts
- buildSrc/build.gradle.kts
- examples/android-gradle/build.gradle
- plugin-build/build.gradle.kts
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
- settings.gradle.kts
> Remove JCenter

- .github/workflows/test-publish-dry-run.yaml
Fixes #123 
I've tested the change locally and it's green. Waiting for a first CI result.
> Add a workflow step for App Bundles

- CHANGELOG.md
- buildSrc/expected-checksums.sha
- plugin-build/download-sentry-cli.sh
> Bump sentry-cli to 1.65.0

- gradle/wrapper/gradle-wrapper.properties
- plugin-build/gradle/wrapper/gradle-wrapper.properties
> Bump Gradle 7.0.2

- .github/workflows/build.yml
- plugin-build/Makefile
Generates distribution artifacts on GHA.
> ci(dist): Generate distribution artifacts in GHA

- buildSrc/src/main/java/BuildUtils.kt
- plugin-build/build.gradle.kts
> Clean ded code releaseSigningEnabled

- .github/workflows/test-publish-dry-run.yaml
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt
> Run tests on AGP 7 stable and Gradle 7.1.1

- .github/workflows/pre-merge.yaml
- .github/workflows/test-publish-dry-run.yaml
- .github/workflows/test-publish.yaml
> Do not call tasks on CI, assemble tasks should be enough to trigger task execution

- buildSrc/src/main/java/Dependencies.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/Instrumentable.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/database/AndroidXSQLiteClassVisitor.kt
* Bumps AGP version to 7.0+ to use new [transform APIs](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/variant/Component.html#transformclasseswith)
* Adds basic structure and classes for bytecode instrumentation
https://github.com/getsentry/sentry-java/issues/1571
Manually for now
> feat: transform api agp

- .github/workflows/pre-merge.yaml
> Remove token from pre merge

- .github/workflows/build.yml
- .github/workflows/test-publish-dry-run.yaml
- CHANGELOG.md
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- examples/android-gradle-kts/build.gradle.kts
- plugin-build/build.gradle.kts
Part of #109 and #180 
Closes #179
> Bump AGP to 7.0.1

- .github/workflows/test-publish-dry-run.yaml
- CHANGELOG.md
- buildSrc/src/main/java/Dependencies.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt
> Bump to AGP 7.0.2

- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/AndroidXRoomDao.kt
> Minor cleanup

- buildSrc/src/main/java/Dependencies.kt
- examples/android-gradle-kts/build.gradle.kts
- examples/android-gradle/build.gradle
https://github.com/getsentry/sentry-android-gradle-plugin/pull/226#issuecomment-962684752
> Add canAutoUpload check because of fork PRs

- buildSrc/src/main/java/Dependencies.kt
- examples/android-ndk/build.gradle
continuation of https://github.com/getsentry/sentry-android-gradle-plugin/pull/227
ran locally
> Fix CI auto upload for forks

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/AndroidXRoomDao.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/AbstractRoomVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/Common.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomQueryVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomQueryWithTransactionVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomTransactionVisitor.kt
Change the Room queries description to fully-qualified class name of the Dao
Ran existing tests
> Change description of Room queries to Dao classname

- CHANGELOG.md
- examples/android-room/src/main/AndroidManifest.xml
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/AbstractSpanAddingMethodVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanOperations.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/AbstractRoomVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/database/visitor/ExecSqlMethodVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/database/visitor/QueryMethodVisitor.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/statement/visitor/ExecuteStatementMethodVisitor.kt
Change the db operation name according to https://github.com/getsentry/develop/pull/452
Closes #220 
Manually again, while #221 is still not implemented
> ref: Update db span operation name

- .github/ISSUE_TEMPLATE/bug_report.md
For context see https://github.com/getsentry/sentry-android-gradle-plugin/pull/242#pullrequestreview-841963060
> meta: Default label for issue template

- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryCliProvider.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPropertiesFileProvider.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTask.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt
* Add a comment clarifying afterEvaluate usage
* Replace standard logging with SentryLogging extensions
> ref: Replace standard logging calls with SentryLogging

- .editorconfig
- .github/workflows/benchmark-build-speed.yml
- scripts/benchmark/README.md
- scripts/benchmark/benchmark-build-speed
- scripts/benchmark/benchmark-build-speed.sh
- scripts/benchmark/duckduckgo/add-sentry-to-duckduckgo.patch
- scripts/benchmark/duckduckgo/duckduckgo.scenarios
> feat: Add benchmark script to measure build speed with and w/o SAGP

- .github/workflows/integration-tests.yml
- scripts/add-sentry-to-iosched.patch
> fix iosched tests

- .github/workflows/integration-tests.yml
- scripts/add-sentry-to-iosched.patch
> Pipe and upload device logs for integration tests

- .github/workflows/integration-tests.yml
> Disable integration tests as they are flaky

- .github/workflows/test-publish-dry-run.yaml
- buildSrc/src/main/java/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
- plugin-build/build.gradle.kts
- plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryPluginTest.kt
> AGP bumps and build improvements

- .github/workflows/pre-merge.yaml
- gradle.properties
- plugin-build/Makefile
- plugin-build/gradle.properties
- plugin-build/src/test/resources/testFixtures/appTestProject/gradle.properties
Similar to https://github.com/getsentry/sentry-java/pull/1896
> Fix daemon and jvmargs

- .craft.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- build.gradle.kts
- scripts/bump-version.sh
- scripts/post-release.sh
> Feat: Use Craft and Publish

- .github/CODEOWNERS
@cortinico so you are not bothered by everything, but just where you're tagged/interested in :) 
> Remove cortinico from CODEOWNERS

- scripts/post-release.sh
Similar to https://github.com/getsentry/sentry-java/pull/1952
> Fix post-release script

- CHANGELOG.md
> Update changelog for 3.0.0

- README.md
> Add Blog posts section to Readme

- dangerfile.js
> Danger PR number as markdown link 

- plugin-build/build.gradle.kts
- plugin-build/download-sentry-cli.sh
- plugin-build/expected-checksums.sha
- plugin-build/sentry-cli.properties
- plugin-build/src/main/resources/bin/.gitignore
to enable automatic updates in CI, as seen in https://github.com/getsentry/sentry-unity/pull/855
locally and checked the CI output
> chore: migrate CLI version specification to a properties file

- .github/workflows/update-deps.yml
depends on #335 
part of https://github.com/getsentry/team-mobile/issues/7
> chore: CLI dependency update CI

- .github/workflows/update-deps.yml
> Use different CI key for running update workflow

- .github/workflows/benchmark-build-speed.yml
- CHANGELOG.md
- scripts/benchmark/benchmark-build-speed.sh
- scripts/benchmark/duckduckgo/add-sentry-to-duckduckgo.patch
- scripts/benchmark/duckduckgo/duckduckgo.scenarios
> Update duckduckgo benchmark git patch

- .github/workflows/danger.yml
- scripts/benchmark/duckduckgo/duckduckgo.scenarios
> Use shared Danger workflow and reduce benchmarking time

- CHANGELOG.md
> Fix unreleased section of CHANGELOG.md

- .github/workflows/test-publish-dry-run.yaml
- plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryPluginTest.kt
> Bump AGP to 8.0.0 stable in test matrix

- plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt
> Hook source context tasks with assemble for AGP 7.4+

- plugin-build/src/main/kotlin/io/sentry/android/gradle/extensions/SentryPluginExtension.kt
Update the java docs to reflect how the code behaves.
only java docs change
> Update `includeNativeSources` docs

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanOperations.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/AbstractRoomVisitor.kt
Change span op for room spans, so they don't contribute to starfish by default
> Change room span op name to db.sql.room

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstall.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstallState.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/quartz/QuartzInstallStrategy.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/autoinstall/quartz/QuartzInstallStrategyTest.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginAutoInstallNonAndroidTest.kt
Auto install for `sentry-quartz` from SDK version `6.30.0`
More magic
> Auto install `sentry-quartz` if `quartz` is installed

- .github/CODEOWNERS
> Add Alex to CODEOWNERS

- CHANGELOG.md
Already updated the Release pages
> Add self-hosted version requirements to changelog

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTaskTest.kt
> Change cli command from upload-dif to debug-files upload for native symbols

- CHANGELOG.md
- plugin-build/download-sentry-cli.sh
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/608
Based on https://github.com/getsentry/sentry-maven-plugin/pull/39/files
> Add aarch64 sentry-cli

- .github/CODEOWNERS
> Add Stefano to code owners

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstall.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/util/Versions.kt
- plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginAutoInstallTest.kt
Closes #603 
Manually and automated
> Consider sentry-bom version for auto-install

- .github/workflows/build.yml
- CHANGELOG.md
- buildSrc/src/main/java/Dependencies.kt
> Do not package dev.gradleplugins within the plugin

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/ChainedInstrumentable.kt
- plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/695
> Remove excessive info logging

- CHANGELOG.md
- examples/android-ndk/build.gradle
- plugin-build/sentry-cli.properties
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/697
> Fix auth-token error for ProGuard mapping upload, even when mapping upload is disabled

- .github/workflows/benchmark-build-speed.yml
- .github/workflows/build.yml
Committed via https://github.com/asottile/all-repos
> all-repos: update actions/upload-artifact to v4

- CHANGELOG.md
- plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/797
> Ensure DexGuard flavor/buildtype mapping files are respected as well

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> chore: Adds default issue types to issue templates

- gradle/libs.versions.toml
Bump proguard and buildconfig plugin versions
> Bump Proguard and BuildConfig

- .github/dependabot.yml
Add dependabot for Github Actions
> Add dependabot for Github actions

- build.gradle.kts
- examples/multi-module-sample/build.gradle.kts
- examples/multi-module-sample/spring-boot-in-multi-module-sample/build.gradle.kts
- examples/multi-module-sample/spring-boot-in-multi-module-sample2/build.gradle.kts
- examples/spring-boot-sample/build.gradle.kts
- plugin-build/build.gradle.kts
- sentry-kotlin-compiler-plugin/build.gradle.kts
Use task configuration avoidance
From 77 tasks: https://scans.gradle.com/s/hogmma5ukrlns/performance/configuration#summary-tasks-created-during-configuration
Down to 62 tasks: https://scans.gradle.com/s/tyoajvbgva7ns/performance/configuration?openScriptsAndPlugins=WyJjb2RlLXVuaXQtaW8uc3ByaW5nLmRlcGVuZGVuY3ktbWFuYWdlbWVudCIsImNvZGUtdW5pdC1ncm9vdnktZ3JhZGxlLXBsdWdpbiJd#summary-tasks-created-during-configuration
> Use task configuration avoidance

- .editorconfig
I took some options from here: https://github.com/facebook/ktfmt/blob/main/docs/editorconfig/.editorconfig-google
I can copy all of them if we think it makes sense.
> Update editorconfig to match ktfmt

- buildSrc/src/main/java/Dependencies.kt
- gradle/libs.versions.toml
This proguard version now matches what is in libs.versions.toml
Spotless is a patch update.
> Bump Spotless and Proguard

- README.md
This was previously picking any branch builds.
> Set Readme badges to main branch builds
