src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy
The sentry gradle plugin does not seem to support multiple application modules in the same gradle project very cleanly. I read https://github.com/getsentry/sentry-android-gradle-plugin/issues/5 but the solution suggested there did not seem ideal.
Allow the sentry.properties file to exist in all currently supported locations, as well as the module's directory.
Ie, both of the following paths would be supported:
```
.
├── app-1
├── app-2
└── sentry.properties
.
├── app-1
│   └── sentry.properties
└── app-2
└── sentry.properties
```
I built a snapshot of the gradle plugin and applied it to my own project (already set up to use sentry). I built release APKs of the app with `sentry.properties` in the root gradle directory, and another with it in the application gradle module directory Crashed …
=> Allow module level sentry properties file

.github/workflows/test-publish.yaml, examples/android-gradle-kts/build.gradle.kts, examples/android-gradle-kts/src/main/AndroidManifest.xml, examples/android-gradle-kts/src/main/java/com/example/sampleapp/MainActivity.java, examples/android-gradle/build.gradle, examples/android-gradle/src/main/AndroidManifest.xml, examples/android-gradle/src/main/java/com/example/sampleapp/MainActivity.java
I'm adding a workflow to test end-to-end that the publishing works fine.
This workflow relies on the API token secret and works only on merge and PRs within the upstream repo.
For external PRs it won't run (as the secret won't be available) as it would just fail.
I've done a test run on my fork with a dummy token here: https://github.com/cortinico/sentry-android-gradle-plugin/runs/2034278777?check_suite_focus=true
=> Add a workflow to test publishing of mapping files

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryProguardConfigTask.groovy
The `validatePlugin` task is currently broken as there is a non annotated property inside a task. I'm fixing it.
=> Fix broken validatePlugin check

.github/workflows/test-publish.yaml
Calling `persistSentryProguardUuidsForReleaseRelease` directly will result in not having a mapping file, so I'm adding `assembleRelease` to the build step.
=> Make sure the `assembleRelease` task is invoked

plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
Just a small test as tests are failing on Windows due to a path separator issue.
Here the run on my fork: https://github.com/cortinico/sentry-android-gradle-plugin/actions/runs/634024107
=> Fix failing Gradle tests on Windows 

plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/TestUtils.kt
It seems that tests are failing on the `ZipFile` when trying to read an asset file from the APK.
I'm updating them to use `ZipInputStream` here.
A green run on CI is here: https://github.com/cortinico/sentry-android-gradle-plugin/actions/runs/651464179
=> Fix flaky test failures for `ZipFile`

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryCliProvider.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryCliProviderTest.kt
Taking some of the work from #44, I've moved all the CLI logic to a separate file and rewritten it in Kotlin + I've added some tests.
Differently than #44 I haven't created a separate task for it as I think it would introduce more complexity.
=> Export the Cli provider outside the plugin

plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryCliProviderTest.kt
Turns out there are some broken tests as the `resources/bin/` folder was excluded by the .gitignore. I'm renaming it to `dummy-bin` so tests should be green after this.
=> Fix broken test on cli from resources 

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
Moved all the task providers to a separate file and added test coverage for them.
Plus I've updated all the parameters from `ApplicationVariant` to `String` so become trivial to test.
=> Export Task Providers to a separate class

build.gradle.kts, buildSrc/src/main/java/Dependencies.kt, plugin-build/build.gradle, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
I'm removing the explicit KtLint version declaration so that `ktlint-gradle` will pick the preferred one. Also there was a failure on the branch on `SentryTaskProviderTest.kt`, this PR is addressing it.
=> Remove Explicit KtLint version

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryMappingFileProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryCliProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryMappingFileProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/utils/SystemPropertyRule.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/utils/WithSystemProperty.kt
This PR converts the `getMappingFile` to Kotlin + adds tests for it.
Moreover, I had to introduce the `SystemPropertyRule`. The reason is that changing properties with `System.setProperty` was causing property values to be retained, hence adding flakiness to tests.
Here a green CI run: https://github.com/cortinico/sentry-android-gradle-plugin/runs/2331188077
=> Export MappingFileProvider

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPropertiesFileProvider.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPropertiesFileProviderTest.kt
Converting another section of the plugin to Kotlin 🎉 
Some of the paths used for search of the properties file are debatable (specifically those on the root projects). I can't seem to figure out why someone would place the property there. @marandaneto do you have some context?
The rest of the PR is mostly tests.
=> Export PropertiesFileProvider

.github/workflows/test-publish-dry-run.yaml, plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryMappingFileProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
This PR removes all the code that is needed to support AGP 3.x
There is a bit more to cleanup inside the Plugin code, but those will be addressed once the plugin class is converted to Kotlin
=> Drop support for AGP 3.x

plugin-build/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTaskTest.kt
The `uploadNativeSymbols` task had his task-action inlined in the plugin apply function. I'm exporting it to a proper Task class and rewriting it in Kotlin here.
=> Export UploadNativeSymbols to its own task

plugin-build/build.gradle.kts
We conditionally apply the maven.publish plugin only if we're on Gradle 6.6.0+
as such plugin is not compatible with lower versions of Gradle and will break
the CI matrix.
Here a green run: https://github.com/cortinico/sentry-android-gradle-plugin/actions/runs/795218822
=> Conditionally apply maven.publish

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt
Fixes #82.
We only wire the upload mapping task if variant buildType has
minifyEnabled to true, which basically hints that proguard
rules will run.
Note that I got rid of `variant.register` since I believe we do not need it as we already wire the task manually. Happy to leave it there if needed.
Note that we still create the task eagerly for now, which is to be tackled in another PR.
This follows a discussion with @marandaneto about #82
Published locally and ensured green build in debug variant where minifyEnabled is false.
=> Fix: Only wire upload mapping task if minifyEnabled

.github/workflows/test-publish.yaml
The `test-publish` workflow should run only on PRs from local branches or on merges. It should not run on PRs from external forks as the secrets are not exposed hence it will fail.
It will fix the CI failure of PR #93
=> Skip publish workflow on PRs from forks

.github/workflows/pre-merge.yaml, .github/workflows/test-publish-dry-run.yaml, examples/android-gradle-kts/build.gradle.kts, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
Adding an entry for AGP `7.x` to both the CI and the test matrix.
I've also cleaned up the matrix a bit, removing `experimental` (I was planning to use it for AGP 7.x but turns out is green already) and the `name` parameter. I've added the `java` parameter to properly configure the Java version.
Fixes #89 
Tests are green locally (as long as you run them on Java 11+).
=> Add AGP 7.x to the CI Matrix

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryMappingFileProvider.kt
Fixes #29
Change the Mapping File Provider to use `isPresent` from the Provider API.
I've also lowered the logging to `info` from `warning`.
=> Silence the missing mapping file warnings

CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/expected-checksums.md5, buildSrc/expected-checksums.sha, plugin-build/download-sentry-cli.sh, plugin-build/src/main/resources/bin/.gitignore
Fixes #103 
I've extended the condition to decide when to download the sentry CLI with a check upon the local MD5 hash. I believe that's simple enough to protect against stale version of the CLI.
Tested locally, works fine so far.
I've added a comment on the `shouldDownloadSentryCli` function to remind to update the `expected-checksums.md5` file once the CLI gets bumped. Not a major deal but the CLI will be re-downloaded every time otherwise.
=> Add support for hashing the CLI

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingTaskTest.kt
I've cherry-picked the commits on #85 + I've applied 2943df5 to make sure we can leverage task configuration avoidance.
I had to remove the `Property<UUID>` as that was forcing the `generateUuidTask` task to be created at configuration time. Now the connection point between the two task is the output asset folder.
Closes #85
Fixes #84 
JUnit tests are attached.
=> Support Configuration Avoidance

plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryPluginUtilsTest.kt
Moving `capitalizeUS` inside `SentryPluginUtils` so it will become `internal` and won't bleed into the consumer build logic.
I've added a couple of tests more.
=> Make capitalizeUS internal

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
Enhancement: Clean up deprecated/removed Dex and Transform tasks.
Tasks dont exist anymore using AGP 4.0.0, See Gradle scan
https://scans.gradle.com/s/qxa77lro2mu52/timeline
Fix https://github.com/getsentry/sentry-android-gradle-plugin/issues/124
=> Enhancement: Clean up deprecated/removed Dex and Transform tasks

.github/workflows/pre-merge.yaml, CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/TestUtils.kt, plugin-build/src/test/resources/testFixtures/appTestProject/sentry.properties
Fix: Only upload debug symbols for non debuggable App
#138
running locally
=> Fix: Only upload debug symbols for non debuggable App

.craft.yml, CHANGELOG.md
Craft's [Changelog Policies](https://github.com/getsentry/craft#changelog-policies) show valid examples of changelogs. Versions should be in heading level 2 (instead of the current 1). This will allow automating the release process using Craft.
=> ref(changelog): Make versions heading level 2

scripts/bump-version.sh
At the moment, the version in `plugin-build/gradle.properties` has to be updated manually before doing a release. The `scripts/bump-version.sh` will be run by Craft before doing a release, and it will set the correct version in that properties file.
=> feat(release): Set plugin version on pre-release

scripts/post-release.sh
Incrementing the version before the release sets a fixed version until the next release it's made. For testing purposes, it's interesting to have a different version name that doesn't match the name of the version in production (ending with `-SNAPSHOT`). Versions are incremented by increasing by one the last numeric value; for example, `1.2.3` will become `1.2.4`, and `1.2.5-beta.1` will become `1.2.5-beta.2`. The first version in these examples is the released version (the argument Craft takes). Note, however, that versions must end with a number: `1.2.3-alpha` is a semantic version but not compatible with this post-release script (doesn't end with a number), and `1.2.3-alpha.0` should be used instead.
=> feat(release): Update plugin version and make it snapshot in post-release

.github/workflows/danger.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/pre-merge.yaml, .github/workflows/test-maven-publish-maven-local.yaml, .github/workflows/test-publish-dry-run.yaml, .github/workflows/test-publish.yaml
In order to get the artifacts that may be generated when doing a release, release branches must run CI.
=> ci(release): Run CI on release branches

CHANGELOG.md, plugin-build/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt
This PR adds 3 fields to the extension to offer filtering capabilities for variant/buildtypes/flavors:
```
sentry {
ignoredVariants = ["..."]
ignoredBuildTypes = ["..."]
ignoredFlavors = ["..."]
}
```
I refactored a bit the tests and created a new `VariantTest` integration test to test only this (otherwise adding flavors to the original test would have complicated task names unnecessarily).
Fixes #18 
Integration tests are included
=> Add support for variant filtering

build.gradle.kts
create alias for closeAndReleaseRepository from project root
since we can't do `gradlew plugin-build:closeAndReleaseRepository`, because its a composite build, craft fails due to `closeAndReleaseRepository` not found in the project root, also doing `./plugin-build/gradlew closeAndReleaseRepository` also does not work since it executes the gradlew in the current folder anyway, not sure if the alias is the best way but it should fix the issue right now.
=> create alias for closeAndReleaseRepository from project root

plugin-build/build.gradle.kts
Zip artifacts per distribution
zipping with the default task was a problem since there were multiple files with the same name and this would fail during Craft execution, now it creates 2 zip files.
=> Zip artifacts per distribution

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
Changes the Plugin to use TaskProviders instead of tasks directly to ensure that tasks from AGP are not configured eagerly.
[Lazy Configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html) "can avoid resource intensive work during the configuration phase, which can have a large impact on build performance". 
The newly added test verifies that no additional tasks are being configured when invoking the `help` task.
=> Lazy configuration

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt
This PR changes the paths hardcoded to `build/` into `project.buildDir`.
Fixes #157	
Will rely on JUnit tests to verify that everything works as usual.
=> Do not hardcode the build/ folder

buildSrc/build.gradle.kts
When doing a Gradle sync in IntelliJ, the CLIs got downloaded every time for me. My guess is that because it configures **all** projects (buildSrc and root in our case), and since we use relative paths there, when configuring the root project `:` (see the screenshot), it couldn't locate the CLIs properly. So I've just changed it to rely on the `rootDir`
See above
=> fix: Cli downloading every Gradle sync

.github/workflows/build.yml, CHANGELOG.md
Fix: missing sentry-cli on embedded resources
`plugin-buikd/make all` does not trigger the `shouldDownloadSentryCli` method from buildSrc, hence the release 2.1.1 didn't have the embedded sentry-cli version
=> Fix: missing sentry-cli on embedded resources

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTask.kt
Invocation of Task.project is forbidden at execution time to comply with configuration cache requirements.
This was the last instance of Task.project that was making config cache fail for my project.
Fixes Gradle configuration cache compliance.
=> Fix: Use task logger instead of project logger

.github/workflows/test-publish.yaml
This relaxes the `test-publish` condition to run if the owner is `getsentry` (either from a local PR or a merge).
Fixes #169 
Will check if the PR is green just after merging this
=> Run publish also on merges

CHANGELOG.md, plugin-build/download-sentry-cli.sh, plugin-build/expected-checksums.sha
Includes a fix needed by the Dart/Flutter SDK:
https://github.com/getsentry/sentry-dart/issues/591#issuecomment-930388078
=> bump sentry-cli 1.69.1

.craft.yml
Craft requires, from https://github.com/getsentry/craft/pull/271, to set the Android config in the `maven` target. This PR updates that config.
=> build(craft): Disable android on `maven` target

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt
Use `SentryGenerateProguardUuidTask.outputDirectory` rather than sharing a property created outside.
When writing Gradle tasks it's important to correctly hook up your task dependencies. If a task uses the output directory of another task the first task should ideally use the output property of the second task (an explicit dependency is also OK).
Secondly, when adding a directory to a sourceset and that directory is the output directory of a task then the property of the task should be added, not just the directory. This will correctly hook up the dependencies for tasks that use that source set. This will prevent warnings such as this (which the Sentry plugin currently produces):
```
> Task :app:lintVitalAnalyzeRelease
Execution optimizations have been disabled for task …
```
=> Fix a task dependency issue

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt
`SentryPluginExtension.tracingInstrumentation` is now public
It's customary to both offer an accessor as well as a function that accepts an `Action` to configure an object. This way you can both access it using the `sentry.tracingInstrumentation.enabled = true` syntax as well as `sentry.tracingInstrumentation { enabled = true }` syntax.
No testing needed since it's just a visibility change.
=> Make tracingInstrumentation public

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt
The changed properties are better suited as sets values should be unique.
This is technically a breaking change but a major release is coming up and I doubt it will cause any issues since it's mostly source compatible.
Set properties are more semantically correct since the properties are used to filter objects.
I ran the tests, no changes.
=> Make the ignoreXXX properties in SentryPluginExtension SetProperty

CHANGELOG.md, examples/android-gradle-kts/build.gradle.kts, examples/android-gradle/build.gradle, examples/android-ndk/build.gradle, examples/android-room/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingTaskTest.kt, plugin-build/src/test/resources/testFixtures/appTestProject/app/build.gradle
This PR essentially includes two changes:
1. Add the `includeProguardMapping` to exclude all the Proguard related code (defaulted to true).
2. Deprecate `autoUpload` in favor of `autoUploadProguardMapping`.
If this lands the documentation should be updated as well.
* Fixes #238 
Unit tests are attached.
To be precise there is a breaking change in the Task API but IIRC that's not a major deal as we don't expect users to use the task directly.
=> Introduce the includeProguardMapping option and deprecate autoUpload

plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/TracingInstrumentationExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/fakes/TestSpanAddingParameters.kt
* Adds new `features` configuration option under the `tracingInstrumentation` sub-extension. This allows specifying a set of features enabled for bytecode manipulation, currently only contains `FILE_IO` and `DATABASE` respectively.
=> feat: Auto-Instrumentation features configuration

buildSrc/src/main/java/Dependencies.kt, plugin-build/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/TracingInstrumentationExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/Instrumentable.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkState.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginCheckAndroidSdkTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginVariantTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/fakes/BaseTestLogger.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/fakes/TestSpanAddingParameters.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkCheckerTest.kt, plugin-build/src/test/resources/testFixtures/appTestProject/gradle.properties
Add a sentry-android SDK version check in the projects.afterevaluate step
This is necessary to avoid breaking customers' code at runtime, for instance, if they are using an older version of `sentry-android` which does not contain file I/O runtime classes. So we just disable the auto-instrumentation features based on the main SDK version
=> feat: Add sentry-android sdk version check

.github/workflows/build.yml, .github/workflows/pre-merge.yaml, .github/workflows/test-publish-dry-run.yaml, .github/workflows/test-publish.yaml, buildSrc/src/main/java/Dependencies.kt
Replace manual `./gradlew` calls with `gradle/gradle-build-action` invocations
Fixes #168 
Let's let the CI tell us the truth.
There are currently two "blockers" to this:
1. `test-publish.yaml` is using `| tee gradle.log` that is not supported by this action. This is used to verify that native symbols are effectively uploaded. 
2. `build.yaml` is using a makefile to make Gradle invocations.
Therefore we end up having a mixture of Gradle invocations & caching mechanisms on Github Actions. I'm unsure if we want to go this way or not.
=> Use gradle-build-action

CHANGELOG.md, plugin-build/download-sentry-cli.sh, plugin-build/expected-checksums.sha
As the title says, this bumps the CLI to 1.72.0
Fixes #260 
Will wait for a green CI,
=> Bump sentry-cli to 1.72.0

.github/ci-gradle.properties, .github/workflows/pre-merge.yaml, CHANGELOG.md, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/data/TracksDao.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/AbstractRoomVisitor.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomQueryVisitor.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomQueryWithTransactionVisitor.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/room/visitor/RoomTransactionVisitor.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginCheckAndroidSdkTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginWithFirebaseTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/VisitorTest.kt
* Do not rely on `visitFrame` calls during instrumentation, as they can be skipped depending on flag set to the AGP (the flag can be overridden by any plugin doing bytecode transformation)
* Adapted VisitorTest to reflect AGP behavior
* Added integration test with firebase-perf plugin
Closes #228
=> fix: Do not rely on visitFrame calls 

CHANGELOG.md, gradle.properties, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/services/SentrySdkStateHolder.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/buildServices.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginCheckAndroidSdkTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginWithFirebaseTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/fakes/TestSpanAddingParameters.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkCheckerTest.kt
* Uses [afterResolve](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvableDependencies.html#afterResolve-org.gradle.api.Action-) callback from configuration to check the sentry-android SDK state (this is called during the execution phase, so we got rid of `afterEvaluate`, and, therefore, warnings about resolving dependencies at configuration phase)
* Uses [shared build services](https://docs.gradle.org/current/userguide/build_services.html) to persist the SDK state across builds and also during the build, if the transforms/tasks run in parallel. This does not use the sdk-state file anymore and resolves the problem that the file was deleted when a build had been run like `./gradlew clean assembleDebug` with parallel execution enabled (basically fixes #255).
Closes …
=> fix: Do not resolve dependencies at configuration time

CHANGELOG.md, plugin-build/build.gradle.kts, plugin-build/src/main/groovy/io/sentry/android/gradle/util/GroovyCompat.groovy, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingTaskTest.kt, scripts/add-sentry-to-iosched.patch
This PR adds support for Dexguard (sits on top of #263 - so please consider only https://github.com/getsentry/sentry-android-gradle-plugin/commit/d297c1460b4a9b7ef4883c62a41c9301a38988d1)
There are a couple of things that are worth discussing:
Before I spend more time on this, I'd like to get some input and feedback.
Fixes #60 
Due to the nature of this change, I've just tested it locally.
=> Add Support for Dexguard

examples/android-guardsquare-proguard/build.gradle, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPluginExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryPluginUtilsTest.kt
This PR sits on top of #267 and adds a `experimentalGuardsquareSupport` that enables/disables  
the whole Proguard/External Dexguard logic and makes it opt-in.
The relevant commit is 39bdece
See discussion in #267
Tested with the sample project + JUnit
Docs should be updated once we finalize the naming.
=> Add the `experimentalGuardsquareSupport` flag

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/Versions.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/AgpVersionsTest.kt
We were breaking the kotlin-gradle-plugin and its IDE integration, because we were requesting our transform on all configurations, and the kotlin plugin seems to be collecting dependencies for IDE integration (imports) from the compileClasspath configuration. Since we are using the same attribute for the transform as AGP (`processed-jar`), we intervene into the transform chain and this seems to break the [collection logic](https://cs.android.com/android-studio/kotlin/+/master:libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/android/internal/AndroidDependencyResolver.kt;l=187-191) of the kotlin plugin. So I simply changed to requesting the transform on the runtimeClasspath configuration, because ASM is also just run for runtime and that fixed the …
=> Fix MetaInfStripTransform breaking Kotlin IDE plugin

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/wrap/visitor/WrappingVisitor.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginWithPlayCoreTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/wrap/visitor/WrappingVisitorTest.kt
* Capture the original variable index of the instrumented type to later use it when storing a wrapped type
Closes #286
=> Fix instrumenting obfuscated libs (play-core)

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/wrap/visitor/WrappingVisitor.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginWithMinifiedLibsTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/wrap/visitor/WrappingVisitorTest.kt
* Fix another edge-case with obfuscate library (use of uninitialized instance)
Discussed this with Bruno - it's fine to ship it as part of a new 3.1.0-beta.1 (which we anyway wanted to release and promote on wizard to prompt users for auto-installation). Also, to avoid craft issues when releasing from a tag rather than `main`.
Closes #304 
If this happens again we should prioritize #306 over the new issues to unblock users without disabling entire auto-instrumentation.
=> Fix obfuscated libs instrumentation (adcolony)

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/okhttp/OkHttp.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
The Okhttp version `3.x` hasn't been instrumented because the class was located in a different folder. This PR fixes it by instrumenting both old and new location.
Manually and automated with integration test
=> fix: Okhttp v3 was not instrumented

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt
Fixes #370
See #370 for further context. This is needed for Gradle 8 support.
Will rely on CI tests.
=> Update DirectoryProperty to use @InputDirectory

.github/CODEOWNERS
@adinauer I guess it's fine to replace you, since you're switching teams anyway. For Java of course it makes sense to keep you there
=> Add Markus to codeowners

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/util/ConstantPoolHelpers.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/util/MinifiedClassDetectionTest.kt
Some class names were classified as minified, causing them to be skipped from any automatic instrumentation.
As discussed checking the class name for being lowercase could be a strong indicator and should work well enough for our use cases.
=> Fix short class names should not be flagged as minified

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTask.kt
* Ensure clean state before generating a new uuid by deleting the old `sentry-debug-meta.properties` file
Potentially fixes #415 
manually + automated
=> Ensure clean state for GenerateUuidTask

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
* Do not register task if the dependencies report flag is turned off. This will prevent configuration cache from being discarded, as the task will not even be created.
Part of #407 
manually and automated
=> Do not register dependencies report task if it's disabled

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/dependencies/SentryExternalDependenciesReportTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/dependencies/SentryExternalDependenciesReportTaskFactory.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/dependencies/SentryExternalDependenciesReportTaskV2.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/ArtifactUtils.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/Versions.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginConfigurationCacheTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryExternalDependenciesReportTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/dependencies/SentryExternalDependenciesReportTaskTest.kt
* Adds a new task which is used for Gradle 7.5 and above, where we can pass the configuration resolution results as a proper task input and it respects configuration cache
Closes #407 
Closes #404
=> Support configuration cache in dependencies report task

CHANGELOG.md, buildSrc/src/main/java/Dependencies.kt, examples/spring-boot-sample/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/statement/AndroidXSQLiteStatement.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/androidx/sqlite/statement/visitor/ExecuteStatementMethodVisitor.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/services/SentryModulesService.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkChecker.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryModulesCollector.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/Versions.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginCheckAndroidSdkTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/VisitorTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryAndroidSdkCheckerTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryModulesCollectorTest.kt
Due to the recent `2.3.0` release of `androidx.sqlite:sqlite-framework:2.3.0`([link]( https://developer.android.com/jetpack/androidx/releases/sqlite#version_230_3)) which is used by room `2.5.0` our bytecode instrumentation fails and causes a runtime crash.
Fixes #434
Sadly just some manual testing, ideally we can have automated tests for this and make the instrumentation itself more stable, any input welcome!
=> Fix failing room 2.5.0 instrumentation

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginWithDependencyCollectorsTest.kt
Integration test against different community gradle plugins that resolve dependency tree.
Should be green after https://github.com/getsentry/sentry-java/pull/2578 is merged and shipped, and we bump the version of the runtime SDK here.
=> Add integration test with other plugins that resolve dependency tree

plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt
:scroll: Description
Fixes Gradle 8 "Task x uses this output of task y without declaring an
explicit or implicit dependency." error##
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/445
=> Fix Gradle 8 dependency issue for uploadNativeSymbols task

CHANGELOG.md, plugin-build/buildSrc/src/main/kotlin/io/sentry/android/gradle/internal/BootstrapAndroidSdk.kt
Parse the sdk name in BootstrapAndroidSdk
Some sdks like Tiramisu or UpsideDownCake are installed creating a folder with the full name instead of the version number. Our plugin check the latest sdk version, but parsing the name as integer make it crash.
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/474
=> Parse the sdk name in BootstrapAndroidSdk

.github/workflows/build.yml, .github/workflows/integration-tests-sentry-cli.yml, .github/workflows/integration-tests.yml, .github/workflows/pre-merge.yaml, .github/workflows/test-publish-dry-run.yaml, .github/workflows/test-publish.yaml
There is a security alert from dependabot saying that we should update to v2.4.2 of the github action. https://github.com/getsentry/sentry-android-gradle-plugin/security/dependabot/1
This changes the commit hash to the latest one (which is equal to 2.4.2).
We are actually not affected by this, because there are no entries of `configuration-cache-*` in our action caches, but still good to bump this:
https://github.com/getsentry/sentry-android-gradle-plugin/actions/caches
=> Bump gradle-build-action to resolve secruity issue

.craft.yml, CHANGELOG.md, plugin-build/build.gradle.kts
Apparently the plugin marker pom file is missing in order to correctly apply our Kotlin Compiler Plugin.
=> Add missing Kotlin Compiler Plugin Marker config

CHANGELOG.md, examples/spring-boot-sample/build.gradle.kts, examples/spring-boot-sample/sentry.properties, plugin-build/build.gradle.kts, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/JavaVariant.kt, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/SentryVariant.kt, plugin-build/src/agp70/kotlin/io/sentry/android/gradle/AGP70Compat.kt, plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPropertiesFileProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/BundleSourcesTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/CollectSourcesTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/SourceContext.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/UploadSourceBundleTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt, plugin-build/src/main/kotlin/io/sentry/jvm/gradle/SentryJvmPlugin.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryNonAndroidPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryKotlinCompilerPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginIntegrationTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/TestUtils.kt, settings.gradle.kts
Collect, bundle and upload sources to Sentry for Java Backend etc. as well. `sentry-debug-meta.properties` is generated and added to the JAR.
To enable source context.
manually
=> Source Context for Java

.github/workflows/update-deps.yml
Allow us to manually trigger the update-dependencies GH action.
So we can trigger it to create a PR for updating e.g. the Java SDK dependency more quickly.
=> Allow manually starting the update-dependencies GH action

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/BundleSourcesTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/SourceContext.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/UploadSourceBundleTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/BaseSentryNonAndroidPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextTest.kt
Pass `Provider<String>` instead of `String?` into tasks so they can lazily resolve the sentry `org` and `project` properties.
`org` and `project` in `sentry` config block was ignored.
Manually
=> No longer ignore `org` and `project` in `sentry` config block

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/extensions/SentryPluginExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/SourceContext.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginIntegrationTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentrySourceContextTest.kt
Rename `project` to `projectName` in SentryPluginExtension
`project` would shadow the Gradle `project` variable preventing users from accessing it, e.g. to use `project.findProperty`.
=> Rename `project` to `projectName` in SentryPluginExtension

plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/services/SentryModulesService.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/Versions.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginTest.kt
added minimum version of sentry-android-okhttp 6.20.0 to enable okhttp event listener instrumentation
(feature was not merged yet, so no need for changelog entry)
Okhttp event listener instrumentation uses `SentryOkHttpEventListener`, which was introduced only in Sentry Android SDK version 6.20.0
Unit test
=> Add okhttp event listener only on sentry above 6.20

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/spring/SpringBoot2InstallStrategy.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/spring/SpringBoot3InstallStrategy.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginAutoInstallNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/autoinstall/spring/SpringBoot2InstallStrategyTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/autoinstall/spring/SpringBoot3InstallStrategyTest.kt
Use Spring Boot autoconfigure modules (`sentry-spring-boot` and `sentry-spring-boot-jakarta`) for auto install
After introducing new modules for autoconfigure and making our starter modules bring `spring-boot-starter` this is needed to avoid `StackOverflowException` when combining SAGP with certain other build tool plugins.
=> Use Spring Boot autoconfigure modules (`sentry-spring-boot` and `sentry-spring-boot-jakarta`) for auto install

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AbstractInstallStrategy.kt
Users get confused and think this means auto install doesn't work especially for Spring (Boot) where we have two sets of integrations (jakarta and non-jakarta) available and there should only ever be one that's installed.
Closes #549
=> Reduce log level from warn to info for some auto install messages

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/extensions/SentryPluginExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/BundleSourcesTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/SourceContext.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/UploadSourceBundleTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/BundleSourcesTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/UploadSourceBundleTaskTest.kt
A new option `url` which is passed through to `sentry-cli`.
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/571
Unit tests, manually
=> Add url option which is passed through to sentry-cli

plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryPluginMRJarTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginKotlinCompilerTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginWithDependencyCollectorsNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginWithDependencyCollectorsTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginWithFirebaseTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginWithMinifiedLibsTest.kt
In case a Gradle build fails, simply print the the build log to make it easier to find the root cause.
Manual test runs
=> Print Gradle build error in case build fails

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt
In theory we could even fail the build, but I don't dare doing that because not sure how it will behave for custom build logic, so warning is good enough
Closes #301 
Manually
=> Print a warning if the plugin is not applied on the app module

CHANGELOG.md, examples/android-guardsquare-proguard/build.gradle, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/extensions/SentryPluginExtension.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/services/SentryModulesService.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/SentryPluginUtils.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryModulesCollectorTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SentryPluginUtilsTest.kt
* Rename `experimentalGuardsquareSupport` flag to `dexguardEnabled`
* Add tracking for dexguard so we can see its adoption
Closes #518
=> Rename `experimentalGuardsquareSupport` flag to `dexguardEnabled`

CHANGELOG.md, examples/android-instrumentation-sample/build.gradle.kts, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/JavaVariant.kt, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/SentryVariant.kt, plugin-build/src/agp70/kotlin/io/sentry/android/gradle/AGP70Compat.kt, plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt
* This was the last remaining thing which was using an older AGP API, now we have proper decoupling per agp-compat source set
Closes #109 
Manually + automated
* Eventually we'd need to configure tasks on the `SentryVariant` level to have it abstracted away, and then we could even move everything to the `common` module and it could be shared between Android and Jvm plugins. Probably gonna be part of #403
=> Use new AGP api for native symbols upload

CHANGELOG.md, plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/extensions/TracingInstrumentationExtension.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt
* Add new `excludes` option to exclude classes from instrumentation. The option just wires to the existing [excludes API](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/variant/Instrumentation#excludes()) from AGP, and only available on AGP 7.4+
Closes #306 
Closes #218 
Manually + automated
=> Add new 'excludes' option to exclude classes from instrumentation

.github/workflows/test-matrix-agp-gradle.yaml, CHANGELOG.md, buildSrc/src/main/java/Dependencies.kt, examples/android-gradle-kts/build.gradle.kts, examples/android-gradle/build.gradle, examples/android-guardsquare-proguard/build.gradle, examples/android-instrumentation-sample/build.gradle.kts, examples/android-instrumentation-sample/sentry.properties, examples/android-ndk/build.gradle, plugin-build/src/main/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryService.kt, plugin-build/src/test/resources/testFixtures/appTestProject/app/build.gradle, plugin-build/src/test/resources/testFixtures/appTestProject/gradle.properties
* Disables telemetry for the test fixture project to not flood sentry with CI events
* Retrieve sentryOrg from the extension, if it's not available in extra properties
* Also, don't set it to `-`, because it means it's empty on the cli
=> Retrieve org from extension, disable telemetry on CI

CHANGELOG.md, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/EditActivity.kt, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/LyricsActivity.kt, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/MainActivity.kt, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/list/TrackAdapter.kt, plugin-build/gradle.properties
* Bump runtime sdk version to 7.0.0 and update broken sources
* Revamp changelog entry
=> Changelog and v7 bump

.github/workflows/pre-merge.yaml, CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTaskTest.kt
For some reason our cli is very picky about parameter position
```shell
sentry-cli --url https://myserver.invalid/ login # works
sentry-cli login --url https://myserver.invalid/ # fails
```
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/609
Added a unit test. In the long run it could make sense to have a base class ~`BaseSentryCliTask`, as we have similar logic spread out a few times already.
=> Fix url parameter position

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/appstart/ContentProviderMethodVisitor.kt
App startup instrumentation fails for some pre-bundled libraries due to bytecode optimizations which produce non spec-compliant JVM bytecode.
As an example the stack frame variable of member functions at index 0 is not a `this` reference anymore.
This mainly affects `ContentProvider` instrumentation as those (opposed to `Application` classes) are usually shipped within libraries.
Affected Examples:
* `com.google.mlkit.common.internal.MlKitInitProvider`
* `androidx.startup.InitializationProvider`
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/618
Manual testing
=> Fix VerifyError when optimized code is instrumented

CHANGELOG.md, plugin-build/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryCliProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/BundleSourcesTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/SourceContext.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/sourcecontext/UploadSourceBundleTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryService.kt, plugin-build/src/main/kotlin/io/sentry/jvm/gradle/SentryJvmPlugin.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryCliProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryNonAndroidPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginConfigurationCacheTest.kt
* Use [ValueSource](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ValueSource.html) or project.provider to defer sentry-cli path calculation to the point where it's actually needed 
Closes #613 
Manually and automated
=> Make sentry-cli path calculation configuration-cache compatible

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt
Fallback to findTask if assembleProvider is null when hooking source bundle and native symbols upload tasks
@krystofwoldrich had problems on his machine although on mine it somehow just worked 🤷 
Manually + automated
=> Fallback to findTask if assembleProvider is null

.github/workflows/build.yml, .github/workflows/integration-tests-sentry-cli.yml, .github/workflows/pre-merge.yaml, .github/workflows/test-matrix-agp-gradle.yaml, .github/workflows/test-publish.yaml, buildSrc/src/main/java/Dependencies.kt, plugin-build/build.gradle.kts, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryPluginTest.kt
* Bumps AGP versions to the latest unstable ones
* Only run the build artifacts job for the `release/**` branches, we don't need other ones similar to sentry-java
* Add a check if pom can be found in the final zip archive
Closes #213
=> Bump AGP versions and run only artifacts job for release

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryService.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryNonAndroidPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginConfigurationCacheTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTelemetryTest.kt
* Do not run sentry-cli commands if telemetry is disabled
* Add `--log-level=error` for the `sentry-cli info` command to prevent printing this message
```
INFO    2024-01-08 10:16:18.758013 +01:00 Loaded file referenced by SENTRY_PROPERTIES (<redacted>)
```
* Uncomment telemetry tests as they should be working now
* ignoreExitValue for deleting lock files, this should fix failures on AGP 8.4.0-alpha06 on `main`
Closes #626
=> Do not run sentry-cli commands if telemetry is disabled

.github/workflows/test-matrix-agp-gradle.yaml, CHANGELOG.md, plugin-build/build.gradle.kts
Seems like `dev.gradleplugins:gradle-api` was bundled with the plugin for compatibility reasons, removing the compatibility block fixes it
Closes #656 
`./gradlew build --scan`
=> Do not pollute build classpath

.github/workflows/test-publish.yaml
Since we're now caching the tasks there was no upload, but we wanna deliberately test this, so disabling the cache for this specific job
=> Run without build cache to verify upload

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/SentryTaskProviderTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt
Based on the task graph for R8/DG, `mergeDex<Variant>` is the closest to `minify<Variant>WithR8`. 
1) hooked ProGuard UUID gen task to the minify/mergeDex tasks
2) hooked UUID upload to assemble task (same as source context)
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/679
Not sure if we still need `transformClassesAndResourcesWithProguardTransformFor*`!?
Manual testing with example app.
=> Fix circular dependency for minify/dexguard

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryService.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryServiceTest.kt
Telemetry uses `sentry-cli info` to gather some env setup information. However, if no auth token is present the stderr is printed and shown as an error in IDEs like Android Studio.
As it can be fine for `sentry-cli info` to fail, simply swallow and re-print the std err and fallback to a default config.
=> Fix misleading auth-token error message in case "sentry-cli info" fails

CHANGELOG.md, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/JavaVariant.kt, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/SentryVariant.kt, plugin-build/src/agp70/kotlin/io/sentry/android/gradle/AGP70Compat.kt, plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/telemetry/SentryTelemetryService.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextTest.kt
* Exclude sources that contain build config in their path (considering well-known community plugins for buildConfig generation as well)
Closes #692 
Closes #683 
Manually verified with the sample from #692 + also automated test
=> Exclude BuildConfig sources from source bundles

CHANGELOG.md, sentry-kotlin-compiler-plugin/build.gradle.kts, sentry-kotlin-compiler-plugin/gradle.properties, sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/SentryKotlinCompilerPlugin.kt, sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension.kt, sentry-kotlin-compiler-plugin/src/test/kotlin/io/sentry/compose/JetpackComposeInstrumentationTest.kt
As of now:
```
DEFAULT
java.lang.NoSuchFieldError: DEFAULT
at com.tschuchort.compiletesting.KotlinCompilation.<init>(KotlinCompilation.kt:143)
at io.sentry.compose.JetpackComposeInstrumentationTest$Fixture.compileFile(JetpackComposeInstrumentationTest.kt:83)
```
```
w: No definition of androidx.compose.ui.Modifier found, Sentry Kotlin Compiler plugin won't run. Please ensure you're applying to plugin to a compose-enabled project.
```
Support K2, fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/698
=> Add support for Kotlin K2 compiler plugin

CHANGELOG.md, sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension.kt
Replace all `impl` usages with either `DeclarationIrBuilder` or other extension functions, which are both available in 1.x and 2.0.0.
Support K2
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/698
=> Support K2 alongside 1.8.x / 1.9.x

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt
Flutter isn't using the transform API to add generated sources, and thus breaks our Android transform API approach.
Simply wire up the task manually until flutter will eventually switch to the transform API as well.
More details on the overall problem: https://www.notion.so/sentry/ProGuard-Mapping-File-upload-sentry-vs-the-rest-e90c1fd768a94bfdb4e0a9ad0ac80503?pvs=4#42b4620bf43349ae9fd091b7c36dda0a
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/701
=> Manually wire up copyFlutterAssets task

CHANGELOG.md, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/JavaVariant.kt, plugin-build/common/src/main/kotlin/io/sentry/gradle/common/SentryVariant.kt, plugin-build/src/agp70/kotlin/io/sentry/android/gradle/AGP70Compat.kt, plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextTest.kt
Looks like Gradle has a bug where it queries values of providers using `.zip` or `.flatMap` too early, but using `.map` works, so we just use that + `.get()` for other providers (which will be still evaluated lazily  since it's inside `.map` I believe)
Closes #683 
See updated integration test in the diff
=> Fix source context with configuration cache on AGP 8+

CHANGELOG.md, sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension.kt
If the Kotlin Compiler Plugin is applied for non Compose enabled modules, it will cause a crash during app compilation.
Fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/687
Manually
=> Only apply Jetpack Compose instrumentation if Modifier class is available

CHANGELOG.md, buildSrc/src/main/java/Dependencies.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstall.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginAutoInstallNonAndroidTest.kt
Fix plugin for spring-dependency-management 1.1.6.
In the new version of spring-depenency-management some of their action are now executed earlier, causing our install strategies to be executed before the AutoInstallState is correctly initialized.
Fixes #735
=> Fix plugin for spring-dependency-management 1.1.6

CHANGELOG.md, examples/android-instrumentation-sample/build.gradle.kts, examples/multi-module-sample/build.gradle.kts, examples/multi-module-sample/spring-boot-in-multi-module-sample/build.gradle.kts, examples/multi-module-sample/spring-boot-in-multi-module-sample2/build.gradle.kts, examples/spring-boot-sample/build.gradle.kts, plugin-build/build.gradle.kts, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginConfigurationCacheTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextNonAndroidTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginSourceContextTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/SentryGenerateProguardUuidTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/util/SkipOnForksRule.kt
Make sure that the debug UUID computation is deterministic and not cache based on the value of the proguard mapping file.
multiple builds from the same commit with a shared build cache can cause mapping files to be overwritten when they are uploaded to Sentry.
New unit test cases were added
=> Make the Debug UUID a deterministic value based on the proguard mapping file.

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/instrumentation/SpanAddingClassVisitorFactory.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/instrumentation/fakes/TestSpanAddingParameters.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginTest.kt
Add `features`, `logcatEnabled` and `appStartEnabled` params to `SpanAddingClassVisitorFactory` parameters to make sure that if these change, the instrumentation is run again and the cache is invalidated.
Currently, when instrumentation parameters `features`, `logcatEnabled` or `appStartEnabled` change, instrumentation is not run again and the cached instrumentation result is used. I.e. it is not possible to change the feature set without deleting the gradle cache in the home directory.
Fixes [#3595](https://github.com/getsentry/sentry-java/issues/3595)
Added automated test
=> Invalidate instrumentation cache when changing instrumentation features

.github/file-filters.yml, .github/workflows/changes-in-high-risk-code.yml
Implement a mechanism that automatically adds an "alert" comment to PRs if they include changes to files we think have higher potential to break things than others.
same as https://github.com/getsentry/sentry-java/pull/3726
✅ by adding the file-filter.yml introduced in this PR to the list of potentially risky changes and ensuring that an alert is shown
=> chore: Add action to warn about potentially risky PR changes

CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstall.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/graphql/Graphql22InstallStrategy.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/graphql/GraphqlInstallStrategy.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/autoinstall/graphql/Graphql22InstallStrategyTest.kt
Add Auto-Install strategy for graphql-22
Fixes https://github.com/getsentry/sentry-java/issues/3756
=> add AutoInstallStrategy for sentry-graphql-22

.git-blame-ignore-revs
#849 touched many lines and likely impacts the usefulness of `git blame`. With this change, that particular commit will be ignored by `git blame` (feature enabled by default in GitHub in the web view, can be set with `git config blame.ignoreRevsFile .git-blame-ignore-revs` locally).
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
=> Create `.git-blame-ignore-revs` and add #849 to it

CHANGELOG.md, sentry-kotlin-compiler-plugin/src/main/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension.kt
…ount` parameter
Incompatible with Kotlin 2.1.20, See also:
https://github.com/JetBrains/kotlin/commit/dd508452c414a0ee8082aa6f76d664271cb38f2f
Fix building failed with Kotlin 2.1.20 + Sentry Compose Trace
https://github.com/getsentry/sentry-android-gradle-plugin/issues/856
Build with action
=> Fix API incompatibility with Kotlin 2.1.20 for Kotlin Compose Extension

.github/workflows/test-matrix-agp-gradle.yaml, CHANGELOG.md, plugin-build/src/main/kotlin/io/sentry/android/gradle/AndroidComponentsConfig.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/services/SentryModulesService.kt, plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateIntegrationListTask.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/BaseSentryPluginTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/integration/SentryPluginConfigurationCacheTest.kt
The task inputs were not properly wired, so running with config-cache enabled resulted in inconsistent integrations list being written to the manifest + unnecessary task reruns. Using `flatMap` on the input + returning a Provider from `SentryModulesService` fixes the problem.
Fixes #846 
Manually + automated
=> fix(instrumentation): Make SentryGenerateIntegrationListTask configuration-cache compatible

build.gradle.kts, examples/multi-module-sample/spring-boot-in-multi-module-sample/build.gradle.kts, examples/multi-module-sample/spring-boot-in-multi-module-sample2/build.gradle.kts, examples/spring-boot-sample/build.gradle.kts, plugin-build/build.gradle.kts, plugin-build/settings.gradle.kts, sentry-kotlin-compiler-plugin/build.gradle.kts, sentry-kotlin-compiler-plugin/settings.gradle.kts, settings.gradle.kts
This removes some uses of the allprojects block in favor of centralized
dependency management.
=> Centralize dependency management

.github/workflows/build.yml, gradle/libs.versions.toml, plugin-build/build.gradle.kts, plugin-build/gradle.properties, sentry-kotlin-compiler-plugin/build.gradle.kts, sentry-kotlin-compiler-plugin/gradle.properties
This updates the Maven Publish Plugin which should unblock enabling the
configuration cache and also help with updating to Gradle 8.x in this
repo.
The changelog for all the versions is here: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md#version-0180-2021-09-13
Note, we cannot update to a higher version until the build itself is
build with Gradle 8.x or higher.
The api to configure signing was changed in 0.20.0 this is why the
gradle property was adjusted.
=> Update Maven Publish Plugin

.github/workflows/pre-merge.yaml, Makefile, plugin-build/Makefile, sentry-kotlin-compiler-plugin/Makefile
We start from a clean slate on CI so running clean only adds time to the
jobs.
Also it is always recommended to use the daemon especially when running
multiple jobs in order to speed up the build.
=> Remove clean and no-daemon

examples/android-gradle-kts/build.gradle.kts, examples/android-gradle/build.gradle, examples/android-ndk/build.gradle
=> Remove some buildscript blocks

plugin-build/build.gradle.kts
On a modern mac machine with 10+ cores this demands too many workers.
Gradle integration tests are disk bound no I/O bound so this doesn't
speed up the build but significantly increases memory consumption.
CI has only 4 cores anyways so this should have the same effect on CI as before.
=> Reduce number of cores/threads.

CHANGELOG.md, gradle/libs.versions.toml, plugin-build/build.gradle.kts, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/BundleSourcesTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/CollectSourcesTaskTest.kt, plugin-build/src/test/kotlin/io/sentry/android/gradle/tasks/dependencies/SentryExternalDependenciesReportTaskTest.kt
This adds Google Truth assertions for easier debugging in tests.
More information about Truth here: https://truth.dev/
Previous kotlin.test assertions give minimal information and a massive useless stacktrace.
Google Truth assertions:
The Google Truth assertions give a lot more meaningful information to make it easier to debug failed tests.
By running the tests :)
=> Add Google Truth for easier to debug assertions in tests.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/maintainer-blank.yml
replaces usage of GH issue type and platform label to Linear-compatible labels
GH issue types will be deprecated internally by August 14
=> chore(gh): Update GH issue templates for Linear compatibility

CHANGELOG.md, examples/android-instrumentation-sample/build.gradle.kts, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/ComposeActivity.kt, examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/ui/MainActivity.kt, gradle/libs.versions.toml, sentry-kotlin-compiler-plugin/src/kotlin2200/kotlin/io/sentry/compose/JetpackComposeTracingIrExtension22.kt, settings.gradle.kts
- There's no `companion` object in `SentryModifier` because it's an object itself, so we just have to use the instance of the class
- Also updated the sample app so we can use the compiler plugin directly in it without the need to publish it first
Closes #941
Manually verified that composables are tagged and breadcrumbs are created for them + existing tests should cover it
=> fix(kotlin-compiler): Fix Modifier.sentryTag() not found warning
